Riders Module
powwater/vendor_dashboard pull request #56
Opened 2021-03-26 16:07 UTC by jimbrig

see #52

2021-03-26 16:08 UTC, jimbrig commented
@merlinoa ready for review; just added a simple DT

![image](https://user-images.githubusercontent.com/32652297/112660587-ffb93d80-8e2b-11eb-8b46-bac9f78de36d.png)

2021-03-29 13:32 UTC, merlinoa commented on shiny_app/R/5_riders_module.R
> +    id <- session$ns("riders_table")
what is this for?  Remove it if it is not used.

2021-03-29 13:33 UTC, merlinoa commented on shiny_app/R/5_riders_module.R
> +  ns <- session$ns
It looks like this is not being used.  Remove if if it is not being used.

2021-03-29 13:34 UTC, merlinoa commented on shiny_app/R/5_riders_module.R
> +    n_row <- nrow(out)
These `n_row` and `n_col` variables are also not used.  Remove everything that is not used.

2021-03-29 13:36 UTC, merlinoa requested changes
Minor changes to clean up unused code.  Go ahead and merge after code cleanup per my comments.

2021-03-29 14:56 UTC, merged